### ISSUE TITLE
Add Opening and Closing head and body Tags

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/html-basics-well-formed-html-document-lab#2]
The instruction of the headline is wrong, it should be "open and closing head and title"

**Comment by sgharms** [comment]
Thanks! Fixed!

**Comment by sgharms** [comment]
Actually, @Amaaniiv I looked at this and I thought I understood your request, but I think I might not.

We say:

Add opening and closing html tags
Add opening and closing head and body tags
Add title tags

Which makes sense. You add the HTML tag, its two children Head and Body, and then within Body, the title tag. 

What you suggest: "open and closing head and title" might imply that title is on the same level as head, as a direct child of html. That's certainly not the case.

As is, we teach 0th level node (html), 1st level (body/head), and then 2nd level (title)

In the tests, we enshrine that same pattern as well.

So, as such, I think I might not understand your request. Please clarify.

**Comment by sgharms** [comment]
@Amaaniiv Without update from you in 2 business days, I'm going to close this issue pending your update. Please re-open when you have time. Thank you.
